# branches to build
branches:
  # whitelist
  only:
    - master

environment:
  matrix:
  # node.js
    - nodejs_version: "0.10"
    - nodejs_version: "0.12"

# Fix line endings on Windows
init:
  - git config --global core.autocrlf true

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

# build version format
version: "{build}"

build: off

test_script:
  - node --version
  - npm --version
  - cmd: npm test
